# deployment of a pod with a single container running mas
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mas-frontend
  namespace: default
  labels:
    app: mas-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mas-frontend
  template:
    metadata:
      labels:
        app: mas-frontend
        azure.workload.identity/use: "true"
    spec:
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Equal"
        value: "NoSchedule"
        effect: "NoSchedule"
      containers:
      - name: mas
        image: aiopsdemothefoggi.azurecr.io/mas-app-frontend-demo:v0.7
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "2048m"